// API Configuration
const API_URL = 'http://127.0.0.1:5000';

let selectedFile = null;
let currentSummary = null;
let currentStats = null;

// Tab switching
function switchTab(tab) {
    const textTab = document.getElementById('textTab');
    const fileTab = document.getElementById('fileTab');
    const btns = document.querySelectorAll('.tab-btn');
    
    if (tab === 'text') {
        textTab.classList.add('active');
        fileTab.classList.remove('active');
        btns[0].classList.add('active');
        btns[1].classList.remove('active');
    } else {
        textTab.classList.remove('active');
        fileTab.classList.add('active');
        btns[0].classList.remove('active');
        btns[1].classList.add('active');
    }
}

// File upload handling
const fileInput = document.getElementById('fileInput');
if (fileInput) {
    fileInput.addEventListener('change', function(e) {
        if (e.target.files.length > 0) {
            selectedFile = e.target.files[0];
            const fileInfo = document.getElementById('fileInfo');
            fileInfo.innerHTML = `✅ Selected: ${selectedFile.name} (${(selectedFile.size / 1024).toFixed(2)} KB)`;
            fileInfo.style.display = 'block';
        }
    });
}

// Character counter
const textInput = document.getElementById('textInput');
if (textInput) {
    textInput.addEventListener('input', function() {
        const len = this.value.length;
        const counter = document.getElementById('charCount');
        counter.textContent = `${len} characters`;
        
        if (len > 0 && len < 30) {
            counter.style.color = '#f44336';
        } else {
            counter.style.color = '#999';
        }
    });
}

// Show notification
function showNotification(message, isError = false) {
    const notification = document.createElement('div');
    notification.textContent = message;
    notification.className = 'notification';
    if (isError) {
        notification.style.background = '#dc3545';
    } else {
        notification.style.background = '#28a745';
    }
    document.body.appendChild(notification);
    
    setTimeout(() => {
        notification.remove();
    }, 3000);
}

// Copy summary to clipboard
function copySummary() {
    if (!currentSummary) {
        showNotification('No summary to copy! Generate a summary first.', true);
        return;
    }
    
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = currentSummary;
    const plainText = tempDiv.textContent || tempDiv.innerText || currentSummary;
    
    navigator.clipboard.writeText(plainText).then(() => {
        showNotification('✅ Summary copied to clipboard!');
    }).catch(() => {
        showNotification('❌ Failed to copy summary', true);
    });
}

// Download as TXT
function downloadAsTXT() {
    if (!currentSummary) {
        showNotification('No summary to download! Generate a summary first.', true);
        return;
    }
    
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = currentSummary;
    let summaryText = tempDiv.textContent || tempDiv.innerText || currentSummary;
    
    const date = new Date();
    const timestamp = date.toISOString().slice(0, 19).replace(/:/g, '-');
    
    let fileContent = `========================================\n`;
    fileContent += `AI DOCUMENT SUMMARIZER - SUMMARY\n`;
    fileContent += `========================================\n`;
    fileContent += `Generated: ${date.toLocaleString()}\n`;
    if (currentStats) {
        fileContent += `Original Length: ${currentStats.original_length} characters\n`;
        fileContent += `Summary Length: ${currentStats.summary_length} characters\n`;
        fileContent += `Compression: ${currentStats.compression}\n`;
    }
    fileContent += `========================================\n\n`;
    fileContent += `SUMMARY:\n`;
    fileContent += `========================================\n\n`;
    fileContent += summaryText;
    fileContent += `\n\n========================================\n`;
    fileContent += `Generated by AI Document Summarizer\n`;
    fileContent += `========================================\n`;
    
    const blob = new Blob([fileContent], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.href = url;
    link.download = `summary_${timestamp}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    showNotification('✅ TXT file downloaded!');
}

// Download as PDF - COMPLETELY REWRITTEN AND FIXED
function downloadAsPDF() {
    if (!currentSummary) {
        showNotification('No summary to download! Generate a summary first.', true);
        return;
    }
    
    showNotification('📑 Generating PDF, please wait...', false);
    
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = currentSummary;
    const summaryText = tempDiv.textContent || tempDiv.innerText || currentSummary;
    const date = new Date();
    const timestamp = date.toISOString().slice(0, 19).replace(/:/g, '-');
    
    // Create a complete HTML document for PDF
    const pdfWindow = window.open('', '_blank');
    
    pdfWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>AI Document Summarizer - Summary</title>
            <style>
                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }
                body {
                    font-family: 'Segoe UI', Arial, sans-serif;
                    padding: 40px;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                }
                .header {
                    text-align: center;
                    margin-bottom: 30px;
                    padding-bottom: 20px;
                    border-bottom: 3px solid #667eea;
                }
                h1 {
                    color: #667eea;
                    font-size: 28px;
                    margin-bottom: 10px;
                }
                .subtitle {
                    color: #666;
                    font-size: 14px;
                }
                .metadata {
                    background: #f8f9fa;
                    padding: 15px;
                    border-radius: 8px;
                    margin-bottom: 30px;
                    font-size: 12px;
                    border-left: 4px solid #667eea;
                }
                .metadata p {
                    margin: 5px 0;
                }
                .summary-title {
                    font-size: 20px;
                    font-weight: bold;
                    margin: 30px 0 15px 0;
                    color: #333;
                }
                .summary-content {
                    background: #fafafa;
                    padding: 25px;
                    border-left: 4px solid #667eea;
                    margin: 20px 0;
                    font-size: 14px;
                    line-height: 1.8;
                    border-radius: 8px;
                }
                .stats {
                    background: linear-gradient(135deg, #667eea15 0%, #764ba215 100%);
                    padding: 20px;
                    border-radius: 8px;
                    margin: 30px 0;
                    text-align: center;
                }
                .stats h3 {
                    margin-bottom: 10px;
                    color: #667eea;
                }
                .stats-grid {
                    display: flex;
                    justify-content: space-around;
                    margin-top: 15px;
                }
                .stat-item {
                    text-align: center;
                }
                .stat-value {
                    font-size: 24px;
                    font-weight: bold;
                    color: #667eea;
                }
                .stat-label {
                    font-size: 11px;
                    color: #666;
                    margin-top: 5px;
                }
                .footer {
                    text-align: center;
                    margin-top: 50px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    font-size: 11px;
                    color: #999;
                }
                @media print {
                    body {
                        print-color-adjust: exact;
                        -webkit-print-color-adjust: exact;
                    }
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🤖 AI Document Summarizer</h1>
                <p class="subtitle">Intelligent Document Summarization</p>
            </div>
            
            <div class="metadata">
                <p><strong>Generated:</strong> ${date.toLocaleString()}</p>
                ${currentStats ? `
                <p><strong>Original Length:</strong> ${currentStats.original_length.toLocaleString()} characters</p>
                <p><strong>Summary Length:</strong> ${currentStats.summary_length.toLocaleString()} characters</p>
                <p><strong>Compression Ratio:</strong> ${currentStats.compression}</p>
                ` : ''}
            </div>
            
            <div class="summary-title">📋 Summary</div>
            <div class="summary-content">
                ${summaryText.replace(/\n/g, '<br>')}
            </div>
            
            <div class="stats">
                <h3>📊 Statistics</h3>
                <div class="stats-grid">
                    <div class="stat-item">
                        <div class="stat-value">${currentStats ? currentStats.original_length.toLocaleString() : 'N/A'}</div>
                        <div class="stat-label">Original Characters</div>
                    </div>
                    <div class="stat-item">
                        <div class="stat-value">${currentStats ? currentStats.summary_length.toLocaleString() : 'N/A'}</div>
                        <div class="stat-label">Summary Characters</div>
                    </div>
                    <div class="stat-item">
                        <div class="stat-value">${currentStats ? currentStats.compression : 'N/A'}</div>
                        <div class="stat-label">Compression</div>
                    </div>
                </div>
            </div>
            
            <div class="footer">
                Generated by AI Document Summarizer on ${date.toLocaleDateString()}<br>
                Visit: AI Document Summarizer
            </div>
            
            <script>
                // Auto-print and close after printing
                window.onload = function() {
                    setTimeout(function() {
                        window.print();
                        setTimeout(function() {
                            window.close();
                        }, 500);
                    }, 500);
                };
            <\/script>
        </body>
        </html>
    `);
    
    pdfWindow.document.close();
    showNotification('📑 PDF preview opened! Use Ctrl+P to save as PDF.', false);
}

// Download as DOCX
function downloadAsDOCX() {
    if (!currentSummary) {
        showNotification('No summary to download! Generate a summary first.', true);
        return;
    }
    
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = currentSummary;
    let summaryText = tempDiv.textContent || tempDiv.innerText || currentSummary;
    
    const date = new Date();
    const timestamp = date.toISOString().slice(0, 19).replace(/:/g, '-');
    
    const docxContent = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>AI Document Summarizer - Summary</title>
        <style>
            body {
                font-family: 'Calibri', Arial, sans-serif;
                margin: 40px;
                line-height: 1.6;
            }
            h1 { color: #667eea; }
            .header { text-align: center; border-bottom: 2px solid #667eea; padding-bottom: 20px; margin-bottom: 30px; }
            .metadata { background: #f5f5f5; padding: 15px; margin: 20px 0; border-left: 4px solid #667eea; }
            .summary { background: #fafafa; padding: 20px; border-left: 4px solid #667eea; margin: 20px 0; }
            .stats { background: #e8f0fe; padding: 15px; text-align: center; margin: 20px 0; border-radius: 8px; }
            .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🤖 AI Document Summarizer</h1>
            <p>Intelligent Document Summarization</p>
        </div>
        
        <div class="metadata">
            <strong>Generated:</strong> ${date.toLocaleString()}<br>
            ${currentStats ? `
            <strong>Original Length:</strong> ${currentStats.original_length.toLocaleString()} characters<br>
            <strong>Summary Length:</strong> ${currentStats.summary_length.toLocaleString()} characters<br>
            <strong>Compression:</strong> ${currentStats.compression}` : ''}
        </div>
        
        <h2>📋 Summary</h2>
        <div class="summary">
            ${summaryText.replace(/\n/g, '<br>')}
        </div>
        
        <div class="stats">
            <strong>📊 Statistics</strong><br>
            Original: ${currentStats ? currentStats.original_length.toLocaleString() : 'N/A'} characters<br>
            Summary: ${currentStats ? currentStats.summary_length.toLocaleString() : 'N/A'} characters<br>
            Compression: ${currentStats ? currentStats.compression : 'N/A'}
        </div>
        
        <div class="footer">
            Generated by AI Document Summarizer on ${date.toLocaleDateString()}
        </div>
    </body>
    </html>`;
    
    const blob = new Blob([docxContent], { type: 'application/msword' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.href = url;
    link.download = `summary_${timestamp}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    showNotification('✅ DOC file downloaded! (Compatible with Microsoft Word)');
}

// Display summary in output
function displaySummary(summary, stats = null) {
    const outputDiv = document.getElementById('output');
    const exportOptions = document.getElementById('exportOptions');
    
    currentSummary = summary;
    currentStats = stats;
    
    let statsHtml = '';
    if (stats) {
        statsHtml = `
            <div class="summary-stats">
                📊 ${stats.original_length.toLocaleString()} characters → ${stats.summary_length.toLocaleString()} characters (${stats.compression} compression)
            </div>
        `;
    }
    
    outputDiv.innerHTML = `
        <div style="line-height: 1.6; text-align: center; max-width: 100%; margin: 0 auto;">
            ${summary}
        </div>
        ${statsHtml}
    `;
    
    exportOptions.style.display = 'block';
}

// Clear all
function clearAll() {
    if (textInput) {
        textInput.value = '';
        const counter = document.getElementById('charCount');
        if (counter) counter.textContent = '0 characters';
    }
    
    selectedFile = null;
    const fileInputElement = document.getElementById('fileInput');
    if (fileInputElement) fileInputElement.value = '';
    const fileInfo = document.getElementById('fileInfo');
    if (fileInfo) fileInfo.style.display = 'none';
    
    const outputDiv = document.getElementById('output');
    if (outputDiv) {
        outputDiv.innerHTML = '<p class="placeholder">Your summary will appear here</p>';
    }
    
    const exportOptions = document.getElementById('exportOptions');
    if (exportOptions) exportOptions.style.display = 'none';
    
    const errorDiv = document.getElementById('error');
    if (errorDiv) errorDiv.style.display = 'none';
    
    currentSummary = null;
    currentStats = null;
    
    showNotification('🧹 All cleared!');
}

// Show error
function showError(message) {
    const errorDiv = document.getElementById('error');
    errorDiv.textContent = `⚠️ ${message}`;
    errorDiv.style.display = 'block';
    setTimeout(() => {
        errorDiv.style.display = 'none';
    }, 5000);
}

// Main summarize function
async function summarize() {
    const isFileTab = document.getElementById('fileTab').classList.contains('active');
    const loadingDiv = document.getElementById('loading');
    const summarizeBtn = document.getElementById('summarizeBtn');
    const outputDiv = document.getElementById('output');
    const exportOptions = document.getElementById('exportOptions');
    
    try {
        loadingDiv.style.display = 'block';
        summarizeBtn.disabled = true;
        outputDiv.innerHTML = '<p class="placeholder">🤔 AI is analyzing your document...</p>';
        exportOptions.style.display = 'none';
        document.getElementById('error').style.display = 'none';
        
        let response;
        
        if (isFileTab && selectedFile) {
            const formData = new FormData();
            formData.append('file', selectedFile);
            response = await fetch(`${API_URL}/summarize`, {
                method: 'POST',
                body: formData
            });
        } else {
            const text = textInput ? textInput.value.trim() : '';
            if (!text) throw new Error('Please enter some text to summarize');
            if (text.length < 30) throw new Error(`Text too short (${text.length} chars). Minimum 30 characters required.`);
            
            response = await fetch(`${API_URL}/summarize`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ text: text })
            });
        }
        
        const data = await response.json();
        
        if (!response.ok) throw new Error(data.error || 'Summarization failed');
        
        if (data.summary) {
            displaySummary(data.summary, data.stats);
            showNotification('✅ Summary generated successfully!');
        } else {
            throw new Error('No summary received from server');
        }
        
    } catch (error) {
        console.error('Error:', error);
        showError(error.message);
        outputDiv.innerHTML = '<p class="placeholder">❌ Error generating summary. Please try again.</p>';
        exportOptions.style.display = 'none';
    } finally {
        loadingDiv.style.display = 'none';
        summarizeBtn.disabled = false;
    }
}

// Check backend health
async function checkBackend() {
    try {
        const response = await fetch(`${API_URL}/health`);
        if (response.ok) {
            console.log('✅ Backend is healthy');
        }
    } catch (error) {
        console.error('❌ Cannot connect to backend');
        showError('Cannot connect to backend server. Please make sure Flask server is running on port 5000');
    }
}

// Initialize
window.addEventListener('load', () => {
    console.log('🚀 AI Document Summarizer Loaded!');
    console.log('💡 PDF: Opens in new window → Use Ctrl+P to save as PDF');
    setTimeout(() => checkBackend(), 500);
});